### ISSUE TITLE
Radio Groups missing step 1

### ISSUE THREAD

**Issue by yvonne-liu** [oliverjam/learn-html-forms#1]
https://github.com/oliverjam/learn-html-forms#part-three-using-radio-groups

**Comment by oliverjam** [comment]
lol I think I just accidentally put an extra `li` in. There's no content missing as far as I can tell

**Comment by oliverjam** [comment]
Fixed in https://github.com/oliverjam/learn-html-forms/commit/da0158fcfd1af8c5f9e3747cbe3804f34dfec333
